export const PERMISSIONS = {
  /* ──────────────── ACCREDITATIONS ──────────────── */
  VIEW_ACCREDITATION: 'VIEW_ACCREDITATION',
  CREATE_ACCREDITATION: 'CREATE_ACCREDITATION',
  EDIT_ACCREDITATION: 'EDIT_ACCREDITATION',
  DELETE_ACCREDITATION: 'DELETE_ACCREDITATION',

  /* ──────────────── CHAPTERS ──────────────── */
  VIEW_CHAPTER: 'VIEW_CHAPTER',
  CREATE_CHAPTER: 'CREATE_CHAPTER',
  EDIT_CHAPTER: 'EDIT_CHAPTER',
  DELETE_CHAPTER: 'DELETE_CHAPTER',

  /* ──────────────── FORMS ──────────────── */
  VIEW_FORM: 'VIEW_FORM',
  CREATE_FORM: 'CREATE_FORM',
  EDIT_FORM: 'EDIT_FORM',
  DELETE_FORM: 'DELETE_FORM',

  /* ──────────────── FORM SUBMISSIONS ──────────────── */
  VIEW_FORM_SUBMISSION: 'VIEW_FORM_SUBMISSION',
  CREATE_FORM_SUBMISSION: 'CREATE_FORM_SUBMISSION',
  EDIT_FORM_SUBMISSION: 'EDIT_FORM_SUBMISSION',
  DELETE_FORM_SUBMISSION: 'DELETE_FORM_SUBMISSION',

  /* ──────────────── CHECKLISTS ──────────────── */
  VIEW_CHECKLIST: 'VIEW_CHECKLIST',
  CREATE_CHECKLIST: 'CREATE_CHECKLIST',
  EDIT_CHECKLIST: 'EDIT_CHECKLIST',
  DELETE_CHECKLIST: 'DELETE_CHECKLIST',

  /* ──────────────── CHECKLIST SUBMISSIONS ──────────────── */
  VIEW_CHECKLIST_SUBMISSION: 'VIEW_CHECKLIST_SUBMISSION',
  CREATE_CHECKLIST_SUBMISSION: 'CREATE_CHECKLIST_SUBMISSION',
  EDIT_CHECKLIST_SUBMISSION: 'EDIT_CHECKLIST_SUBMISSION',
  DELETE_CHECKLIST_SUBMISSION: 'DELETE_CHECKLIST_SUBMISSION',

  /* ──────────────── POLICIES ──────────────── */
  VIEW_POLICY: 'VIEW_POLICY',
  CREATE_POLICY: 'CREATE_POLICY',
  EDIT_POLICY: 'EDIT_POLICY',
  DELETE_POLICY: 'DELETE_POLICY',

  /* ──────────────── POLICY VERSIONS ──────────────── */
  VIEW_POLICY_VERSION: 'VIEW_POLICY_VERSION',
  CLONE_POLICY_VERSION: 'CLONE_POLICY_VERSION',
  REVIEW_POLICY_VERSION: 'REVIEW_POLICY_VERSION',
  EDIT_POLICY_VERSION: 'EDIT_POLICY_VERSION',
  DELETE_POLICY_VERSION: 'DELETE_POLICY_VERSION',
} as const

export type PermissionKey = keyof typeof PERMISSIONS
export type PermissionValue = (typeof PERMISSIONS)[PermissionKey]
