/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'
import { Route as AuthenticatedRolesRouteRouteImport } from './routes/_authenticated/roles/route'
import { Route as AuthenticatedOrganizationsRouteRouteImport } from './routes/_authenticated/organizations/route'
import { Route as AuthenticatedPolicyPolicyIdRouteRouteImport } from './routes/_authenticated/policy/$policyId/route'
import { Route as AuthenticatedPolicyVersionPolicyVersionIdRouteRouteImport } from './routes/_authenticated/policy-version/$policyVersionId/route'
import { Route as AuthenticatedManageRoleRoleIdRouteRouteImport } from './routes/_authenticated/manage-role/$roleId/route'
import { Route as AuthenticatedFormFormIdRouteRouteImport } from './routes/_authenticated/form/$formId/route'
import { Route as AuthenticatedFormSubmissionFormSubmissionIdRouteRouteImport } from './routes/_authenticated/form-submission/$formSubmissionId/route'
import { Route as AuthenticatedFormEditorFormIdRouteRouteImport } from './routes/_authenticated/form-editor/$formId/route'
import { Route as AuthenticatedChecklistChecklistIdRouteRouteImport } from './routes/_authenticated/checklist/$checklistId/route'
import { Route as AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRouteImport } from './routes/_authenticated/checklist-submission/$checklistSubmissionId/route'
import { Route as AuthenticatedChecklistEditorChecklistIdRouteRouteImport } from './routes/_authenticated/checklist-editor/$checklistId/route'
import { Route as AuthenticatedChapterChapterIdRouteRouteImport } from './routes/_authenticated/chapter/$chapterId/route'
import { Route as AuthenticatedAccreditationCreateRouteRouteImport } from './routes/_authenticated/accreditation/create/route'
import { Route as AuthenticatedAccreditationAccreditationIdRouteRouteImport } from './routes/_authenticated/accreditation/$accreditationId/route'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRouteRoute = AuthenticatedRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRouteRoute =
  AuthenticatedOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPolicyPolicyIdRouteRoute =
  AuthenticatedPolicyPolicyIdRouteRouteImport.update({
    id: '/policy/$policyId',
    path: '/policy/$policyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPolicyVersionPolicyVersionIdRouteRoute =
  AuthenticatedPolicyVersionPolicyVersionIdRouteRouteImport.update({
    id: '/policy-version/$policyVersionId',
    path: '/policy-version/$policyVersionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManageRoleRoleIdRouteRoute =
  AuthenticatedManageRoleRoleIdRouteRouteImport.update({
    id: '/manage-role/$roleId',
    path: '/manage-role/$roleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormFormIdRouteRoute =
  AuthenticatedFormFormIdRouteRouteImport.update({
    id: '/form/$formId',
    path: '/form/$formId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormSubmissionFormSubmissionIdRouteRoute =
  AuthenticatedFormSubmissionFormSubmissionIdRouteRouteImport.update({
    id: '/form-submission/$formSubmissionId',
    path: '/form-submission/$formSubmissionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormEditorFormIdRouteRoute =
  AuthenticatedFormEditorFormIdRouteRouteImport.update({
    id: '/form-editor/$formId',
    path: '/form-editor/$formId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistChecklistIdRouteRoute =
  AuthenticatedChecklistChecklistIdRouteRouteImport.update({
    id: '/checklist/$checklistId',
    path: '/checklist/$checklistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRoute =
  AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRouteImport.update({
    id: '/checklist-submission/$checklistSubmissionId',
    path: '/checklist-submission/$checklistSubmissionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistEditorChecklistIdRouteRoute =
  AuthenticatedChecklistEditorChecklistIdRouteRouteImport.update({
    id: '/checklist-editor/$checklistId',
    path: '/checklist-editor/$checklistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChapterChapterIdRouteRoute =
  AuthenticatedChapterChapterIdRouteRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccreditationCreateRouteRoute =
  AuthenticatedAccreditationCreateRouteRouteImport.update({
    id: '/accreditation/create',
    path: '/accreditation/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccreditationAccreditationIdRouteRoute =
  AuthenticatedAccreditationAccreditationIdRouteRouteImport.update({
    id: '/accreditation/$accreditationId',
    path: '/accreditation/$accreditationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/organizations': typeof AuthenticatedOrganizationsRouteRoute
  '/roles': typeof AuthenticatedRolesRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/accreditation/$accreditationId': typeof AuthenticatedAccreditationAccreditationIdRouteRoute
  '/accreditation/create': typeof AuthenticatedAccreditationCreateRouteRoute
  '/chapter/$chapterId': typeof AuthenticatedChapterChapterIdRouteRoute
  '/checklist-editor/$checklistId': typeof AuthenticatedChecklistEditorChecklistIdRouteRoute
  '/checklist-submission/$checklistSubmissionId': typeof AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRoute
  '/checklist/$checklistId': typeof AuthenticatedChecklistChecklistIdRouteRoute
  '/form-editor/$formId': typeof AuthenticatedFormEditorFormIdRouteRoute
  '/form-submission/$formSubmissionId': typeof AuthenticatedFormSubmissionFormSubmissionIdRouteRoute
  '/form/$formId': typeof AuthenticatedFormFormIdRouteRoute
  '/manage-role/$roleId': typeof AuthenticatedManageRoleRoleIdRouteRoute
  '/policy-version/$policyVersionId': typeof AuthenticatedPolicyVersionPolicyVersionIdRouteRoute
  '/policy/$policyId': typeof AuthenticatedPolicyPolicyIdRouteRoute
}
export interface FileRoutesByTo {
  '/organizations': typeof AuthenticatedOrganizationsRouteRoute
  '/roles': typeof AuthenticatedRolesRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/accreditation/$accreditationId': typeof AuthenticatedAccreditationAccreditationIdRouteRoute
  '/accreditation/create': typeof AuthenticatedAccreditationCreateRouteRoute
  '/chapter/$chapterId': typeof AuthenticatedChapterChapterIdRouteRoute
  '/checklist-editor/$checklistId': typeof AuthenticatedChecklistEditorChecklistIdRouteRoute
  '/checklist-submission/$checklistSubmissionId': typeof AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRoute
  '/checklist/$checklistId': typeof AuthenticatedChecklistChecklistIdRouteRoute
  '/form-editor/$formId': typeof AuthenticatedFormEditorFormIdRouteRoute
  '/form-submission/$formSubmissionId': typeof AuthenticatedFormSubmissionFormSubmissionIdRouteRoute
  '/form/$formId': typeof AuthenticatedFormFormIdRouteRoute
  '/manage-role/$roleId': typeof AuthenticatedManageRoleRoleIdRouteRoute
  '/policy-version/$policyVersionId': typeof AuthenticatedPolicyVersionPolicyVersionIdRouteRoute
  '/policy/$policyId': typeof AuthenticatedPolicyPolicyIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRouteRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRouteRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accreditation/$accreditationId': typeof AuthenticatedAccreditationAccreditationIdRouteRoute
  '/_authenticated/accreditation/create': typeof AuthenticatedAccreditationCreateRouteRoute
  '/_authenticated/chapter/$chapterId': typeof AuthenticatedChapterChapterIdRouteRoute
  '/_authenticated/checklist-editor/$checklistId': typeof AuthenticatedChecklistEditorChecklistIdRouteRoute
  '/_authenticated/checklist-submission/$checklistSubmissionId': typeof AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRoute
  '/_authenticated/checklist/$checklistId': typeof AuthenticatedChecklistChecklistIdRouteRoute
  '/_authenticated/form-editor/$formId': typeof AuthenticatedFormEditorFormIdRouteRoute
  '/_authenticated/form-submission/$formSubmissionId': typeof AuthenticatedFormSubmissionFormSubmissionIdRouteRoute
  '/_authenticated/form/$formId': typeof AuthenticatedFormFormIdRouteRoute
  '/_authenticated/manage-role/$roleId': typeof AuthenticatedManageRoleRoleIdRouteRoute
  '/_authenticated/policy-version/$policyVersionId': typeof AuthenticatedPolicyVersionPolicyVersionIdRouteRoute
  '/_authenticated/policy/$policyId': typeof AuthenticatedPolicyPolicyIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/organizations'
    | '/roles'
    | '/users'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/accreditation/$accreditationId'
    | '/accreditation/create'
    | '/chapter/$chapterId'
    | '/checklist-editor/$checklistId'
    | '/checklist-submission/$checklistSubmissionId'
    | '/checklist/$checklistId'
    | '/form-editor/$formId'
    | '/form-submission/$formSubmissionId'
    | '/form/$formId'
    | '/manage-role/$roleId'
    | '/policy-version/$policyVersionId'
    | '/policy/$policyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/organizations'
    | '/roles'
    | '/users'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/accreditation/$accreditationId'
    | '/accreditation/create'
    | '/chapter/$chapterId'
    | '/checklist-editor/$checklistId'
    | '/checklist-submission/$checklistSubmissionId'
    | '/checklist/$checklistId'
    | '/form-editor/$formId'
    | '/form-submission/$formSubmissionId'
    | '/form/$formId'
    | '/manage-role/$roleId'
    | '/policy-version/$policyVersionId'
    | '/policy/$policyId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/organizations'
    | '/_authenticated/roles'
    | '/_authenticated/users'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/accreditation/$accreditationId'
    | '/_authenticated/accreditation/create'
    | '/_authenticated/chapter/$chapterId'
    | '/_authenticated/checklist-editor/$checklistId'
    | '/_authenticated/checklist-submission/$checklistSubmissionId'
    | '/_authenticated/checklist/$checklistId'
    | '/_authenticated/form-editor/$formId'
    | '/_authenticated/form-submission/$formSubmissionId'
    | '/_authenticated/form/$formId'
    | '/_authenticated/manage-role/$roleId'
    | '/_authenticated/policy-version/$policyVersionId'
    | '/_authenticated/policy/$policyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policy/$policyId': {
      id: '/_authenticated/policy/$policyId'
      path: '/policy/$policyId'
      fullPath: '/policy/$policyId'
      preLoaderRoute: typeof AuthenticatedPolicyPolicyIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policy-version/$policyVersionId': {
      id: '/_authenticated/policy-version/$policyVersionId'
      path: '/policy-version/$policyVersionId'
      fullPath: '/policy-version/$policyVersionId'
      preLoaderRoute: typeof AuthenticatedPolicyVersionPolicyVersionIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-role/$roleId': {
      id: '/_authenticated/manage-role/$roleId'
      path: '/manage-role/$roleId'
      fullPath: '/manage-role/$roleId'
      preLoaderRoute: typeof AuthenticatedManageRoleRoleIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/form/$formId': {
      id: '/_authenticated/form/$formId'
      path: '/form/$formId'
      fullPath: '/form/$formId'
      preLoaderRoute: typeof AuthenticatedFormFormIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/form-submission/$formSubmissionId': {
      id: '/_authenticated/form-submission/$formSubmissionId'
      path: '/form-submission/$formSubmissionId'
      fullPath: '/form-submission/$formSubmissionId'
      preLoaderRoute: typeof AuthenticatedFormSubmissionFormSubmissionIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/form-editor/$formId': {
      id: '/_authenticated/form-editor/$formId'
      path: '/form-editor/$formId'
      fullPath: '/form-editor/$formId'
      preLoaderRoute: typeof AuthenticatedFormEditorFormIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist/$checklistId': {
      id: '/_authenticated/checklist/$checklistId'
      path: '/checklist/$checklistId'
      fullPath: '/checklist/$checklistId'
      preLoaderRoute: typeof AuthenticatedChecklistChecklistIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist-submission/$checklistSubmissionId': {
      id: '/_authenticated/checklist-submission/$checklistSubmissionId'
      path: '/checklist-submission/$checklistSubmissionId'
      fullPath: '/checklist-submission/$checklistSubmissionId'
      preLoaderRoute: typeof AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist-editor/$checklistId': {
      id: '/_authenticated/checklist-editor/$checklistId'
      path: '/checklist-editor/$checklistId'
      fullPath: '/checklist-editor/$checklistId'
      preLoaderRoute: typeof AuthenticatedChecklistEditorChecklistIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chapter/$chapterId': {
      id: '/_authenticated/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/chapter/$chapterId'
      preLoaderRoute: typeof AuthenticatedChapterChapterIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accreditation/create': {
      id: '/_authenticated/accreditation/create'
      path: '/accreditation/create'
      fullPath: '/accreditation/create'
      preLoaderRoute: typeof AuthenticatedAccreditationCreateRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accreditation/$accreditationId': {
      id: '/_authenticated/accreditation/$accreditationId'
      path: '/accreditation/$accreditationId'
      fullPath: '/accreditation/$accreditationId'
      preLoaderRoute: typeof AuthenticatedAccreditationAccreditationIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrganizationsRouteRoute: typeof AuthenticatedOrganizationsRouteRoute
  AuthenticatedRolesRouteRoute: typeof AuthenticatedRolesRouteRoute
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccreditationAccreditationIdRouteRoute: typeof AuthenticatedAccreditationAccreditationIdRouteRoute
  AuthenticatedAccreditationCreateRouteRoute: typeof AuthenticatedAccreditationCreateRouteRoute
  AuthenticatedChapterChapterIdRouteRoute: typeof AuthenticatedChapterChapterIdRouteRoute
  AuthenticatedChecklistEditorChecklistIdRouteRoute: typeof AuthenticatedChecklistEditorChecklistIdRouteRoute
  AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRoute: typeof AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRoute
  AuthenticatedChecklistChecklistIdRouteRoute: typeof AuthenticatedChecklistChecklistIdRouteRoute
  AuthenticatedFormEditorFormIdRouteRoute: typeof AuthenticatedFormEditorFormIdRouteRoute
  AuthenticatedFormSubmissionFormSubmissionIdRouteRoute: typeof AuthenticatedFormSubmissionFormSubmissionIdRouteRoute
  AuthenticatedFormFormIdRouteRoute: typeof AuthenticatedFormFormIdRouteRoute
  AuthenticatedManageRoleRoleIdRouteRoute: typeof AuthenticatedManageRoleRoleIdRouteRoute
  AuthenticatedPolicyVersionPolicyVersionIdRouteRoute: typeof AuthenticatedPolicyVersionPolicyVersionIdRouteRoute
  AuthenticatedPolicyPolicyIdRouteRoute: typeof AuthenticatedPolicyPolicyIdRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrganizationsRouteRoute: AuthenticatedOrganizationsRouteRoute,
  AuthenticatedRolesRouteRoute: AuthenticatedRolesRouteRoute,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccreditationAccreditationIdRouteRoute:
    AuthenticatedAccreditationAccreditationIdRouteRoute,
  AuthenticatedAccreditationCreateRouteRoute:
    AuthenticatedAccreditationCreateRouteRoute,
  AuthenticatedChapterChapterIdRouteRoute:
    AuthenticatedChapterChapterIdRouteRoute,
  AuthenticatedChecklistEditorChecklistIdRouteRoute:
    AuthenticatedChecklistEditorChecklistIdRouteRoute,
  AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRoute:
    AuthenticatedChecklistSubmissionChecklistSubmissionIdRouteRoute,
  AuthenticatedChecklistChecklistIdRouteRoute:
    AuthenticatedChecklistChecklistIdRouteRoute,
  AuthenticatedFormEditorFormIdRouteRoute:
    AuthenticatedFormEditorFormIdRouteRoute,
  AuthenticatedFormSubmissionFormSubmissionIdRouteRoute:
    AuthenticatedFormSubmissionFormSubmissionIdRouteRoute,
  AuthenticatedFormFormIdRouteRoute: AuthenticatedFormFormIdRouteRoute,
  AuthenticatedManageRoleRoleIdRouteRoute:
    AuthenticatedManageRoleRoleIdRouteRoute,
  AuthenticatedPolicyVersionPolicyVersionIdRouteRoute:
    AuthenticatedPolicyVersionPolicyVersionIdRouteRoute,
  AuthenticatedPolicyPolicyIdRouteRoute: AuthenticatedPolicyPolicyIdRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
